CREATE DATABASE `app`;
USE `app`;
CREATE TABLE `toSlice` (
    `ID` INT(32) NOT NULL AUTO_INCREMENT,
	`FILE` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_general_ci',
	`PREFIX` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_general_ci',
	`PRINTER` VARCHAR(512) NOT NULL COLLATE 'utf8mb4_general_ci',
	`PRINT_SETTINGS` VARCHAR(512) NOT NULL COLLATE 'utf8mb4_general_ci',
	`FILAMENT` VARCHAR(512) NOT NULL COLLATE 'utf8mb4_general_ci',
	`SLICED` TINYINT(1) NOT NULL DEFAULT '0',
	UNIQUE INDEX `FILE` (`FILE`) USING BTREE,
	INDEX `ID` (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=9
;
