CREATE SEQUENCE toSlice_seq;

CREATE TABLE toSlice (
    ID INT NOT NULL DEFAULT NEXTVAL ('toSlice_seq'),
	FILE VARCHAR(128) NOT NULL,
	PREFIX VARCHAR(32) NOT NULL,
	PRINTER VARCHAR(512) NOT NULL,
	PRINT_SETTINGS VARCHAR(512) NOT NULL,
	FILAMENT VARCHAR(512) NOT NULL,
	SLICED SMALLINT NOT NULL DEFAULT '0',
	CONSTRAINT FILE UNIQUE (FILE)
);

CREATE INDEX ID ON toSlice (ID);